spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    # mongodb:
    #  uri: mongodb+srv://lee38138:Bachkhoa12@lee01.dkroxft.mongodb.net/planb?retryWrites=true&w=majority

  kafka:
    enabled: true
    bootstrap-servers: localhost:9092
    group-id: minh-group
    topic: user-message-topic
    output-topic: output-user-message-topic
    streams:
      table-name: count-table
      state:
        dir: /tmp/kafka

springdoc:
  swagger-ui:
    url:
