spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    # mongodb:
    #  uri: mongodb+srv://lee38138:Bachkhoa12@lee01.dkroxft.mongodb.net/planb?retryWrites=true&w=majority


  kafka:
    enabled: false
    bootstrap-servers: localhost:9092
    topic: user-messages
    group-id: minhle

springdoc:
  swagger-ui:
    url:


